### PR TITLE
Added ability to insert custom CSS

### PR DESCRIPTION
**Pull request by arjanmels**
Adde the ability to add custom CSS. This allows styling of pages with Elements as desired.

### CODE REVIEW

**Comment by Hieromon** [comment]
@arjanmels, In HTML5, I thought that we could place the style elements in the body and intended to be able to generate CSS for a custom web page in the body using AutoConnectElement.
But I found that it is allowed from [HTML5.2](https://www.w3.org/TR/html/document-metadata.html#elementdef-style) of the W3C Recommendation. This is my misunderstanding.

I think PR works well, but it affects the owned page of AutoConnect. Also, the generated HTML will be redundant. Maybe, I should add AutoConnectElement for CSS generation rather than AuConnectConfig extension. What do you think? It will be helpful if you can hear your opinion.

**Comment by arjanmels** [comment]
I think it is actually an advantage that you can also affect the standard AutoConnect pages: allows for some easy custom styling of all pages.
Your idea of an AutoConnectElement also has its merits as it allows per page customization.
Either way would serve my current purpose where I add some CSS to align all input boxes.

**Comment by MingKoo** [comment]
I have a completely different question. I said it here. I'm sorry. The code is:
void delCredential() {
  AutoConnectCredential  ac(CREDENTIAL_OFFSET);
  //AutoConnectCredential();
  struct station_config  entry;
  String content = "";
  uint8_t  count = ac.entries();
  Serial.println(" ");
  Serial.print("Wifi Credentials: ");
  Serial.println(count);
  for (int8_t i = 0; i < count; i++) {    // Loads all entries.
    ac.load(i, &entry);
    content += String((char *)entry.ssid);
    ac.del((char *)entry.ssid);
    Serial.print("SSID: ");
    Serial.print(content);
    Serial.println(" is deleted!");
  }
  Serial.println("ESP RESET...... ");
  ESP.reset();
  }

After the first run of the program, the certificate can be obtained,  However, after reboot the ESP8266,  But  the certificate that have been deleted are still maintained. How did it ?  Now, count is ZERO. 
What should I do?

**Comment by Hieromon** [comment]
@MingKoo, Your question is not appropriate for this PR. Please post it to the issue.
I will prepare an answer and can give some advice.
Thank you.

**Comment by MingKoo** [comment]
> @MingKoo, Your question is not appropriate for this PR. Please post it to the issue.
> I will prepare an answer and can give some advice.
> Thank you.

I have revised it.Thanks.

**Comment by MingKoo** [comment]
@Hieromon Ok.I have revised it.

**Comment by Hieromon** [comment]
@arjanmels I feel hesitant about having an exit that can inadvertently overwrite the AutoConnect standard page CSS which combined with the facility of AutoConnect. The insertion point for the cssExtra source of your PR is at the trailing position of the luxBar style. If the user trying to use this exit does not know the inside of AutoConnect, this may produce different results than my intended behavior.
For the exit functions like this to work properly, the library should equip the checking mechanism for brought changes by the user exit. But the implementation is heavy.
I will add an element that can be styled relatively safely for the AutoConnectAux page as **AutoConnectStyle**. That will solve half of your requirement.

As you pointed out, the current alignment of the input box is a bit wrong. I'm making compromises to keep the CSS code as short as possible. Otherwise, increasing the CSS size may trigger a memory shortage in PageBuilder. This is a structural flaw in PageBuilder.

There is also a proposal to import your CSS code into the library. How about you?

**Comment by arjanmels** [comment]
@Hieromon I agree that checking valid css is way over the top.
You're suggestion of adding an element for the AutoConnectAux page seems a good compromise. That is also my main requirement.

My css is for aligning the fields, but it is not fully generic as it has an absolute size in it: `label+input,label+select { position:sticky; left: 250px; width:300px!important; box-sizing: border-box;}`

**Comment by Hieromon** [comment]
@arjanmels, Added RC version for CSS extension including resolution of label position for PR #99 to Develop branch named Enhance/v0911. The outline of the specification is as follows:

1. CSS extension
    Added new attribute AutoConnectStyle. 

    ```cpp
    AutoConnectStyle(const char* name, const char* value)
    ```
    ```cpp
    ACStyle(name, value)
    ```

    The value specifies string the CSS code for extending the style, and type attribute as **ACStyle** using  AutoConnectStyle in JSON.

    ```json
    {
      "name": "style",
      "type": "ACStyle",
      "value": "label+input,label+select { position:sticky; left:250px; width:300px!important; box-sizing:border-box }"
    }
    ```

    AutoConnectStyle inserts extra CSS into the AutoConnectAux page. The insertion point is at the end of the `<style>` block in the `<head> ~ </ head>` section.
   
    Note: As your suggestion, AutoConnectConfig::extraCSS, has been dropped considering the impact on the behavior of the AutoConnect standard menu.

2. Label position flexibility for Checkbox
    The position of the label belonging to the checkbox can be specified around the element. AutoConnectCheckbox has the **labelPosition** member variable as an attribute to indicate label position.

    ```cpp
    AutoConnectCheckbox(const char* name, const char* value, const char* label, const bool checked, const ACPosition_t labelPosition, const ACPosterior_t post)
    ```

    labelPosition is an **ACPosition_t** enumeration and takes the following values:
    - AC_Infront : Place a label in front of the check box.
    - AC_Behind : Place a label behind the check box.

    Default value is **AC_Behind**.
    The specification of labelPosition when writing AutoConnectCheckbox in JSON depends on the **labelposition** attribute and its value is `infront` or `behind`.

    ```json
    {
      "name": "check",
      "type": "ACCheckbox",
      "value": "check",
      "label": "Check",
      "labelposition": "infront",
      "checked": true
    }
    ````

Please evaluate the above implementation on [Enhance/v0911](https://github.com/Hieromon/AutoConnect/tree/Enhance/v0911) branch.

**Comment by arjanmels** [comment]
@Hieromon It works beautifully. Thank you very much.

I did discover one unrelated bug regarding PSRAM allocation. I have created a separate issue (which includes the solution): #102

**Pull request closed without merging**
